github: [devinschumacher]

open_collective: devinschumacher

custom: [
"http://downloadvimeo.com/",
"https://serpdownloaders.com/vimeo-video-downloader",
"https://apps.serp.co/vimeo-video-downloader",
"https://serp.co/products/vimeo-video-downloader",
"https://downloadingfreevideo.com/",
]

