github: [devinschumacher]
open_collective: devinschumacher
custom: [
"http://downloadvimeo.com/",
"https://apps.serp.co/vimeo-video-downloader",
"https://downloadingfreevideo.com/",
"https://whop.com/serp-downloaders/vimeo-video-downloader/",
"https://serp.co/products/vimeo-video-downloader",
"https://store.serp.co/product-details/product/vimeo-video-downloader",
]

