github: [devinschumacher]
open_collective: devinschumacher
custom: [
"http://downloadvimeo.com/",
"https://apps.serp.co/vimeo-video-downloader",
"https://whop.com/serp-downloaders/vimeo-video-downloader/",
"https://serp.co/products/vimeo-video-downloader",
]

